---

- name: Create a "wordpress" db
  become: true
  mysql_db:
    name: wordpress
    state: present

- name: Create db user 
  become: true
  mysql_user:
    name: wordpress
    password: wordpress
    priv: '*.*:ALL'
    state: present
    
- name: Enable MySQL
  become: true
  service:
    name: mysql
    state: started
